# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import account_2pc_pb2 as account__2pc__pb2

GRPC_GENERATED_VERSION = '1.74.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in account_2pc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TwoPCParticipantStub(object):
    """Node-level 2PC participant API
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrepareCreateAccount = channel.unary_unary(
                '/banking.TwoPCParticipant/PrepareCreateAccount',
                request_serializer=account__2pc__pb2.PrepareCreateAccountRequest.SerializeToString,
                response_deserializer=account__2pc__pb2.PrepareCreateAccountResponse.FromString,
                _registered_method=True)
        self.CommitCreateAccount = channel.unary_unary(
                '/banking.TwoPCParticipant/CommitCreateAccount',
                request_serializer=account__2pc__pb2.CommitCreateAccountRequest.SerializeToString,
                response_deserializer=account__2pc__pb2.Empty.FromString,
                _registered_method=True)
        self.AbortCreateAccount = channel.unary_unary(
                '/banking.TwoPCParticipant/AbortCreateAccount',
                request_serializer=account__2pc__pb2.AbortCreateAccountRequest.SerializeToString,
                response_deserializer=account__2pc__pb2.Empty.FromString,
                _registered_method=True)


class TwoPCParticipantServicer(object):
    """Node-level 2PC participant API
    """

    def PrepareCreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitCreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortCreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwoPCParticipantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrepareCreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareCreateAccount,
                    request_deserializer=account__2pc__pb2.PrepareCreateAccountRequest.FromString,
                    response_serializer=account__2pc__pb2.PrepareCreateAccountResponse.SerializeToString,
            ),
            'CommitCreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitCreateAccount,
                    request_deserializer=account__2pc__pb2.CommitCreateAccountRequest.FromString,
                    response_serializer=account__2pc__pb2.Empty.SerializeToString,
            ),
            'AbortCreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortCreateAccount,
                    request_deserializer=account__2pc__pb2.AbortCreateAccountRequest.FromString,
                    response_serializer=account__2pc__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'banking.TwoPCParticipant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('banking.TwoPCParticipant', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TwoPCParticipant(object):
    """Node-level 2PC participant API
    """

    @staticmethod
    def PrepareCreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.TwoPCParticipant/PrepareCreateAccount',
            account__2pc__pb2.PrepareCreateAccountRequest.SerializeToString,
            account__2pc__pb2.PrepareCreateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitCreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.TwoPCParticipant/CommitCreateAccount',
            account__2pc__pb2.CommitCreateAccountRequest.SerializeToString,
            account__2pc__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortCreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.TwoPCParticipant/AbortCreateAccount',
            account__2pc__pb2.AbortCreateAccountRequest.SerializeToString,
            account__2pc__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
