# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account_2pc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'account_2pc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x63\x63ount_2pc.proto\x12\x07\x62\x61nking\"k\n\x1bPrepareCreateAccountRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x17\n\x0finitial_balance\x18\x04 \x01(\x01\"C\n\x1cPrepareCreateAccountResponse\x12\x13\n\x0bvote_commit\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"4\n\x1a\x43ommitCreateAccountRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"3\n\x19\x41\x62ortCreateAccountRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\x8d\x02\n\x10TwoPCParticipant\x12\x63\n\x14PrepareCreateAccount\x12$.banking.PrepareCreateAccountRequest\x1a%.banking.PrepareCreateAccountResponse\x12J\n\x13\x43ommitCreateAccount\x12#.banking.CommitCreateAccountRequest\x1a\x0e.banking.Empty\x12H\n\x12\x41\x62ortCreateAccount\x12\".banking.AbortCreateAccountRequest\x1a\x0e.banking.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_2pc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREPARECREATEACCOUNTREQUEST']._serialized_start=30
  _globals['_PREPARECREATEACCOUNTREQUEST']._serialized_end=137
  _globals['_PREPARECREATEACCOUNTRESPONSE']._serialized_start=139
  _globals['_PREPARECREATEACCOUNTRESPONSE']._serialized_end=206
  _globals['_COMMITCREATEACCOUNTREQUEST']._serialized_start=208
  _globals['_COMMITCREATEACCOUNTREQUEST']._serialized_end=260
  _globals['_ABORTCREATEACCOUNTREQUEST']._serialized_start=262
  _globals['_ABORTCREATEACCOUNTREQUEST']._serialized_end=313
  _globals['_EMPTY']._serialized_start=315
  _globals['_EMPTY']._serialized_end=322
  _globals['_TWOPCPARTICIPANT']._serialized_start=325
  _globals['_TWOPCPARTICIPANT']._serialized_end=594
# @@protoc_insertion_point(module_scope)
